### ISSUE TITLE
unable to load apns

### ISSUE THREAD

**Issue by anurodhp** [tmolitor-stud-tu/mod_push_appserver#16]
Feb 17 17:29:49 modulemanager	error	Unable to load module 'push_appserver_apns': .../lib/prosody/modules/mod_push_appserver_apns/mod_push_appserver_apns.lua:228: unexpected symbol near ';'

**Comment by tmolitor-stud-tu** [comment]
That seems to be allowed in lua 5.2 but not in 5.1, fixed now
