### ISSUE TITLE
new errors starting up

### ISSUE THREAD

**Issue by anurodhp** [tmolitor-stud-tu/mod_push_appserver#17]
.../mod_push_appserver_apns/mod_push_appserver_apns.lua:264: attempt to index field '?' (a nil value)
Feb 17 17:50:07 general	error	
stack traceback:
	.../mod_push_appserver_apns/mod_push_appserver_apns.lua:264: in function <.../mod_push_appserver_apns/mod_push_appserver_apns.lua:259>
	(tail call): ?
	(tail call): ?
	/usr/lib/prosody/util/timer.lua:51: in function '?'
	/usr/lib/prosody/net/server_select.lua:917: in function </usr/lib/prosody/net/server_select.lua:861>
	[C]: in function 'xpcall'
	/usr/bin/prosody:400: in function 'loop'
	/usr/bin/prosody:431: in main chunk
	[C]: ?
Feb 17 17:50:13 mod_s2s	error	Traceback[s2s]: .../mod_push_appserver_apns/mod_push_appserver_apns.lua:56: attempt to index local 'timer' (a nil value)
stack traceback:
	.../mod_push_appserver_apns/mod_push_appserver_apns.lua:56: in function 'stoppable_timer'
	.../mod_push_appserver_apns/mod_push_appserver_apns.lua:259: in function '?'
	/usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
	(tail call): ?
	(tail call): ?
	...dy/modules/mod_push_appserver/mod_push_appserver.lua:276: in function '?'
	/usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
	(tail call): ?
	/usr/lib/prosody/core/stanza_router.lua:190: in function 'core_post_stanza'
	/usr/lib/prosody/core/stanza_router.lua:137: in function </usr/lib/prosody/core/stanza_router.lua:63>
	...
	[C]: in function 'parse'
	/usr/lib/prosody/util/xmppstream.lua:271: in function 'feed'
	/usr/lib/prosody/modules/mod_s2s/mod_s2s.lua:558: in function 'data'
	/usr/lib/prosody/modules/mod_s2s/mod_s2s.lua:605: in function </usr/lib/prosody/modules/mod_s2s/mod_s2s.lua:602>
	(tail call): ?
	/usr/lib/prosody/net/server_select.lua:879: in function </usr/lib/prosody/net/server_select.lua:861>
	[C]: in function 'xpcall'
	/usr/bin/prosody:400: in function 'loop'
	/usr/bin/prosody:431: in main chunk
	[C]: ?

**Comment by anurodhp** [comment]
is there a software version issue here?

**Comment by tmolitor-stud-tu** [comment]
well, did you get a log entry of level "warn" saying`APNS read error --> resending *all* pending pushes...`?
