### ISSUE TITLE
attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by anurodhp** [tmolitor-stud-tu/mod_push_appserver#18]
Feb 17 23:38:34 general	error	Top-level error, please report:
.../mod_push_appserver_apns/mod_push_appserver_apns.lua:264: attempt to index field '?' (a nil value)
Feb 17 23:38:34 general	error	
stack traceback:
	.../mod_push_appserver_apns/mod_push_appserver_apns.lua:264: in function <.../mod_push_appserver_apns/mod_push_appserver_apns.lua:259>
	(tail call): ?
	(tail call): ?
	/usr/lib/prosody/util/timer.lua:51: in function '?'
	/usr/lib/prosody/net/server_select.lua:917: in function </usr/lib/prosody/net/server_select.lua:861>
	[C]: in function 'xpcall'
	/usr/bin/prosody:400: in function 'loop'
	/usr/bin/prosody:431: in main chunk
	[C]: ?

**Comment by tmolitor-stud-tu** [comment]
Sadly I'm not able to reproduce the error on my machine (real APNS sandbox server and my own emulator).

I promoted the debug logs relevant for this error to "error" level.
Could you please submit the error log (/var/log/prosody/prosody.err after the backtrace occured?

Delete the file before restarting prosody to have a fresh errorlog not containing old entries.

**Comment by tmolitor-stud-tu** [comment]
What prosody version are you using?
I successfully tested the appserver on prosody 0.9 (lua 5.1) and prosody 0.11 (lua 5.2)...

**Comment by anurodhp** [comment]
I’ll check on Saturday and let you know. Likely what ships with Ubuntu

**Comment by tmolitor-stud-tu** [comment]
It would be possible to ignore `nil` values at this point, but this would only cure symptoms and not the cause. I'd rather like to fix the underlying problem.
And for this I need the errorlog (see https://github.com/tmolitor-stud-tu/mod_push_appserver/issues/18#issuecomment-464679877).

Which Ubuntu version do you use? Trusty, Xenial, Bionix or Cosmic?

**Comment by tmolitor-stud-tu** [comment]
Something new? I'd like to fix this nasty bug as soon as possible and release a new version of the appserver.

**Comment by anurodhp** [comment]
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

Prosody 0.10.1

# Lua environment
Lua version:             	Lua 5.1

# Lua module versions
lfs:     	LuaFileSystem 1.6.3
libevent:	2.0.21-stable
luaevent:	0.4.4
lxp:     	LuaExpat 1.3.0
socket:  	LuaSocket 3.0-rc1
ssl:     	0.5.1

**Comment by anurodhp** [comment]
running this right now, no errors observed. I have it running on Monal. Will let you know If all of the issues with ejabberd have been resolved.

**Comment by tmolitor-stud-tu** [comment]
Just to make it clear: the latest version of mod_push_appserver is running without errors now?

**Comment by anurodhp** [comment]
Yes

**Comment by tmolitor-stud-tu** [comment]
nice!! :) I'll remove the debug logging and release a new stable version in the next few days then. Thanks again for your help.

**Comment by tmolitor-stud-tu** [comment]
The new version will have a new rate limit behaviour:
The setting `push_appserver_rate_limit` now sets the number of pushes allowed per second.
In the last release it set the number of seconds to wait between pushes.

I also applied saner defaults to this setting (5 pushes per second).

Please change your configuration if you used this setting before.

**Comment by tmolitor-stud-tu** [comment]
closed (see release v2.0.0)
