### ISSUE TITLE
Recommended configuration approach

### ISSUE THREAD

**Issue by marc0s** [tmolitor-stud-tu/mod_push_appserver#26]
Hi,

I've been reading through the `README.md` and the latest changes and I've noticed that the configuration example uses `Component` instead of `VirtualHost`.

I've been using the `VirtualHost` statement for configuring the push service like in the following:

```lua
VirtualHost "push.example.org" enabled = true;
http_host = "push.example.org";

-- WARNING: in production *PROTECT* the /v1/settings path if enabled!
push_appserver_debugging = true
push_appserver_fcm_key = "SomeKeyForFCM"
push_appserver_apns_cert = "/etc/prosody/certs.d/apns_certificate.pem";
push_appserver_apns_key = "/etc/prosody/certs.d/apns_privkey.pem";

modules_enabled = {
	-- Generally required
		"dialback"; -- s2s dialback support
		"disco"; -- Service discovery
		"rawdebug";
		"posix";
		"push_appserver";
		"push_appserver_apns";
		"push_appserver_fcm";
};

modules_disabled = {
	"register";
};
```

Are there any relevant differences in the result of configuring this module in one way or another?
If, choosing the `Component` approach, would I need to define two different names for each of the push type handlers (fcm and apns)?

Thanks!

**Comment by tmolitor-stud-tu** [comment]
If you use a virtual host you will automatically load all sorts of modules onto the virtual host not really needed. Components are more lightweight.

As for the multiple push backends: I updated the readme to also reflect such a configuration.

**Comment by marc0s** [comment]
Hi,

On 18 February 2020 07:32:59 GMT+01:00, tmolitor-stud-tu <notifications@github.com> wrote:
>If you use a virtual host you will automatically load all sorts of
>modules onto the virtual host not really needed. Components are more
>lightweight.

Understood. That makes sense.

>As for the multiple push backends: I updated the readme to also reflect
>such a configuration.

Thanks a lot!
