### ISSUE TITLE
Kick, invite, message and different notifications

### ISSUE THREAD

**Issue by TonyLead** [tmolitor-stud-tu/mod_push_appserver#29]
Hi

I want to ask, can I send notification when in muc user was banned or kicked or invite to chat? 

Or your library only for message? Thank you

**Comment by tmolitor-stud-tu** [comment]
This is the appserver part of XEP-0357.
Its part of the xmpp server implementation part of this xep as to what notifications/pushes to send.
The appserver merely proxies them through to the app in question.

You can find the XEP including a schematic drawing of the parts in this push system here: https://xmpp.org/extensions/xep-0357.html
