### ISSUE TITLE
Feature Request: multiple APNS  types

### ISSUE THREAD

**Issue by anurodhp** [tmolitor-stud-tu/mod_push_appserver#4]
It would be nice to be able to run both sandbox and prod on the same server. Additionally, being able to run multiple APNS types on the same server would make things easier.  APNS should probably actually be 3 different kinds with separate cert options. 

1. APNS-iOS-sandbox
2. APNS-iOS-production 
3. APNS-macOS

**Comment by tmolitor-stud-tu** [comment]
This already implemented.
Just define different prosody hosts having different options.

Something like "ios.push.monal.im" and "macos.push.monal.im".

Alternatively you could define different components on the same host, I think.
Components can have their own config options, too.

See https://prosody.im/doc/components

**Comment by tmolitor-stud-tu** [comment]
Alternatively just define different components on the same host.
Components can have their own config options, too.

**Comment by tmolitor-stud-tu** [comment]
I'll close this one.

If you have more questions, feel free to ask :)
