### ISSUE TITLE
Invalid syntax? Lua has no support for C-like ternary operator

### ISSUE THREAD

**Issue by marc0s** [tmolitor-stud-tu/mod_push_appserver#7]
https://github.com/tmolitor-stud-tu/mod_push_appserver/blob/98b2aea716ac72b899eb8825d05478e7d1674072/mod_push_appserver_apns/mod_push_appserver_apns.lua#L197

The error is `modulemanager       error	Unable to load module 'push_appserver_apns': ...ody/external-modules/mod_push_appserver_apns/mod_push_appserver_apns.lua:197: unexpected symbol near '?'`

Replacing that statement with `priority = summary["last-message-body"] ~= nil and "high" or "silent";` makes it work.

Would you like me to submit a PR?

**Comment by tmolitor-stud-tu** [comment]
Oh, my bad. I fixed it no need for a pull request, but thanks!
