### ISSUE TITLE
Can't serialize table: table has multiple references

### ISSUE THREAD

**Issue by streaps** [tmolitor-stud-tu/mod_push_appserver#9]
Edit: I was confused. That has nothing to do with this module. Just ignore. Sorry for the noise. 

Another error on Prosody 0.11.1

Dec 29 11:57:12 c2s55e6a95f5fa0 info    Client connected
Dec 29 11:57:15 c2s55e6a95f5fa0 info    Authenticated as user@example.com
Dec 29 11:57:19 c2s55e6a95f5fa0 error   Traceback[c2s]: /usr/lib/prosody/util/serialization.lua:38: Can't serialize table: table has multiple references
stack traceback:
        [C]: in function 'error'
        /usr/lib/prosody/util/serialization.lua:38: in function 'fallback'
        /usr/lib/prosody/util/serialization.lua:135: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:194: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:194: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:194: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:194: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:194: in function 'serialize_table'
        /usr/lib/prosody/util/serialization.lua:220: in function </usr/lib/prosody/util/serialization.lua:218>
        (...tail calls...)
        /usr/lib/prosody/util/datamanager.lua:206: in function </usr/lib/prosody/util/datamanager.lua:195>
        (...tail calls...)
        /opt/prosody-modules/mod_cloud_notify/mod_cloud_notify.lua:116: in function </opt/prosody-modules/mod_cloud_notify/mod_cloud_notify.lua:114>
        (...tail calls...)
        /opt/prosody-modules/mod_cloud_notify/mod_cloud_notify.lua:240: in function '?'
        /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
        (...tail calls...)
        /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
        (...tail calls...)
        /usr/lib/prosody/core/stanza_router.lua:181: in function 'core_post_stanza'
        /usr/lib/prosody/core/stanza_router.lua:127: in function 'core_process_stanza'
        /usr/lib/prosody/modules/mod_c2s.lua:276: in function 'func'
        /usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>

**Comment by tmolitor-stud-tu** [comment]
You are right, this seems to be an error in the push client module of prosody, not this appserver.
But: I'm incidentally also the maintainer of that client module.

This seems to be due to this bug: https://issues.prosody.im/711
Please install prosody 0.11 new enough to include the fix by zash (dated 2018-12-02).

**Comment by streaps** [comment]
Thanks, I updated to 0.11 nightly, which includes the fix.
